#!/usr/bin/env python3

import re
import subprocess
import sys

HEADERS = ["linux/input.h", "linux/input-event-codes.h"]

# prefix -> (table name, type)
GROUPS = {
    "EV_":      "ev_labels",
    "SYN_":     "syn_labels",
    "KEY_":     "key_labels",
    "BTN_":     "key_labels",      # buttons share the EV_KEY namespace
    "REL_":     "rel_labels",
    "ABS_":     "abs_labels",
    "SW_":      "sw_labels",
    "MSC_":     "msc_labels",
    "LED_":     "led_labels",
    "REP_":     "rep_labels",
    "SND_":     "snd_labels",
    "FF_":      "ff_labels",
    "BUS_":     "bus_labels",
    "INPUT_PROP_": "input_prop_labels",
}

# constants that aren't simple numeric defines / are aliases or ranges
SKIP = {
    "EV_VERSION", "EV_MAX", "EV_CNT",
    "KEY_MAX", "KEY_CNT", "KEY_MIN_INTERESTING",
    "BTN_MISC", "BTN_MOUSE",
    "REL_MAX", "REL_CNT",
    "ABS_MAX", "ABS_CNT",
    "SW_MAX", "SW_CNT",
    "MSC_MAX", "MSC_CNT",
    "LED_MAX", "LED_CNT",
    "SND_MAX", "SND_CNT",
    "FF_MAX", "FF_CNT", "FF_EFFECT_MIN", "FF_EFFECT_MAX",
    "FF_WAVEFORM_MIN", "FF_WAVEFORM_MAX",
    "INPUT_PROP_MAX", "INPUT_PROP_CNT",
}

def find_header_path(name):
    # Ask the C preprocessor where it would find this header
    out = subprocess.run(
        ["cpp", "-M", "-x", "c", "-"],
        input=f'#include <{name}>\n',
        capture_output=True, text=True
    ).stdout
    for tok in out.split():
        if tok.endswith(name.split("/")[-1]) and tok != "\\":
            return tok
    return None

def extract_defines(path):
    pat = re.compile(r'^\s*#define\s+([A-Za-z_][A-Za-z0-9_]*)\s+(\S+)')
    defs = {}
    with open(path) as f:
        for line in f:
            m = pat.match(line)
            if not m:
                continue
            name, val = m.group(1), m.group(2)
            defs[name] = val
    return defs

def main():
    all_defs = {}
    for h in HEADERS:
        path = find_header_path(h)
        if not path:
            print(f"warning: could not locate {h}", file=sys.stderr)
            continue
        all_defs.update(extract_defines(path))

    tables = {t: [] for t in set(GROUPS.values())}

    for name in all_defs:
        if name in SKIP:
            continue
        for prefix, table in GROUPS.items():
            if name.startswith(prefix):
                tables[table].append(name)
                break

    # de-dup while preserving first-seen order, then sort by name
    for t in tables:
        tables[t] = sorted(set(tables[t]))

    print("// AUTO-GENERATED by gen_labels.py. do not edit by hand.")
    print("// Constants derived from this system's <linux/input.h> /")
    print("// <linux/input-event-codes.h> headers at build time.")
    print()
    print("#include <linux/input.h>")
    print()
    print("struct label {")
    print("    const char *name;")
    print("    int value;")
    print("};")
    print()
    print("#define LABEL(constant) { #constant, constant }")
    print("#define LABEL_END { NULL, -1 }")
    print()

    for table_name in [
        "input_prop_labels", "ev_labels", "syn_labels", "key_labels",
        "rel_labels", "abs_labels", "sw_labels", "msc_labels",
        "led_labels", "rep_labels", "snd_labels", "bus_labels", "ff_labels",
    ]:
        print(f"static struct label {table_name}[] = {{")
        for name in tables.get(table_name, []):
            print(f"    LABEL({name}),")
        print("    LABEL_END,")
        print("};")
        print()

    # key_value_labels isn't a kernel constant table it's our own
    # small lookup for EV_KEY value field (0/1/2), defined manually.
    print("static struct label key_value_labels[] = {")
    print('    { "UP", 0 },')
    print('    { "DOWN", 1 },')
    print('    { "REPEAT", 2 },')
    print("    LABEL_END,")
    print("};")

if __name__ == "__main__":
    main()
